### PR TITLE
Fix autoLamp and FPS settings

### PR DESCRIPTION
**Pull request by daschr**
Hi,

I've fixed the points in https://github.com/easytarget/esp32-cam-webserver/pull/237#issuecomment-1079668134

I've needed to rename the `cam_streamer.c` to `cam_streamer.cpp` to link against the CPP functions setLamp for the autolamp support.

One minor problem is the definition of MIN_FRAME_TIME and CAM_STREAMER_MAX_CLIENTS in the "myconfig.h", since one cannot simply include it in `app_httpd.cpp` and `cam_streamer.cpp` (redefinition of stationList). Maybe you've got some idea how we can solve this.

Cheers,

David

### CODE REVIEW

**Comment by easytarget** [comment]
Cool. I'm on the road today, will look once home.

I deal with the settings in myconfig .h, it's crude, just processing them in a huge set of `#if defined ...` blocks and then setting an exported global to be included wherever needed. When back at my desktop I can have a look and make a more concrete suggestion.

**Comment by daschr** [comment]
Hi,

one can now set the minimum frame delay (`MIN_FRAME_TIME`) and maximum number of concurrent streaming clients (`CAM_STREAMER_MAX_CLIENTS`). There is a minor change in the myconfig.sample.h; the *stationList* must be *const* (preventing redeclaration of *stationList*).

Cheers,

David

**Comment by daschr** [comment]
Hi @easytarget ,

are there some issues which need to be solved until the multiclient streaming feature gets merged into the main branch?
I'm willed to provide you with more patches for getting it into main.

Cheers,

David

**Comment by easytarget** [comment]
Hi David, 
No, I've just had to focus on some personal and job issues recently and not had any time or mental space for this.  I was also vaguely waiting for Expressif to drop the 2.0.3 core release before I did anything further.

I have, in the menatime been running your code on a test camera very successfully.

My plan is to deal with your branch next. I want to do a 4.1 release with this asap.

**Comment by daschr** [comment]
Hi,

no problem! Take your time.

Cheers,

David

**Comment by easytarget** [comment]
Ok, I just merged this, I'll test locally and see what shakes out.

**Pull request merged**
